import { TotoMessageBus } from "totoms";
import { GaleConfig } from "../../Config";
import { AgentsCatalog } from "../catalog/AgentsCatalog";
import { ConversationStore } from "../../store/ConversationStore";
import { DefaultAgentCallFactory } from "../../api/AgentCall";
import { AgentConversationMessage } from "../../model/AgentMessage";

/**
 * This class contains all the conversation-related logic. 
 * 
 * That means: 
 * - Receiving messages from users and adding them to the conversation and triggering the agents target of the conversation to process the new message
 */
export class Conversation {

    constructor(private config: GaleConfig, private messageBus: TotoMessageBus, private cid: string) { }

    /**
     * This method is called when a new message is sent to an Agent.
     * 
     * @param message the caller's message
     */
    async processNewMessage(message: ConversationMessage): Promise<{ conversationId: string, messageId: string }> {

        const db = await this.config.getMongoDb(this.config.getDBName());
        const conversationStore = new ConversationStore(db, this.config);

        // Store the message (creates a new conversation if needed) and resolve the conversationId
        const { conversationId, messageId } = await conversationStore.storeMessage(message.agentId, message.message, message.userEmail, message.conversationId);

        // Send the message asynchronously to the agent for processing (the agent can decide to process it synchronously or asynchronously, if asynchronously the agent will be responsible to update the conversation with the answer when it's ready)
        const agentMessage: AgentConversationMessage = {
            conversationId,
            messageId,
            agentId: message.agentId,
            message: message.message,
            userEmail: message.userEmail,
        }

        await this.messageBus.publishMessage({ topic: "galeagents" }, {
            type: "agentMessagePosted",
            cid: this.cid,
            id: messageId,
            msg: `New message posted to conversation ${conversationId} for agent ${message.agentId}`,
            timestamp: new Date().toISOString(),
            data: agentMessage
        })

        return { conversationId, messageId };
    }

    /**
     * Sends the message to the agent (synchronourly) for processing.
     * 
     * @param agentMessage 
     */
    async sendMessageToAgent(agentMessage: AgentConversationMessage) {

        const db = await this.config.getMongoDb(this.config.getDBName());

        const agentsCatalog = new AgentsCatalog(db, this.config);
        
        const agentDefinition = await agentsCatalog.getAgent(agentMessage.agentId);

        await new DefaultAgentCallFactory(this.cid, this.config).createAgentCall(agentDefinition).sendMessage(agentMessage);

    }

        
}

export interface ConversationMessage {
    conversationId?: string; // ID of the conversation to which the message belongs (if it's a new conversation, this can be generated by the server and returned in the response)
    agentId: string;        // ID of the agent this message is directed to
    message: string;        // The user message content
    userEmail: string;     // Email of the user who sent the message (useful for personalization or follow-up)
}