import { TotoRuntimeError, ValidationError } from "toto-api-controller";

/**
 * Models the data needed to send a task request TO an Agent (not to Gale Broker).
 * 
 * This is used by Gale Broker to send tasks to agents.
 */
export class AgentTaskRequest {

    correlationId?: string;             // Correlation ID to group related tasks together.
    command: Command;
    taskId: TaskId;                     // Unique identifier of the task to be executed. E.g. "text.summarize"
    taskInstanceId?: string | null;     // Unique identifier for this specific execution of the task. This is generated by Gale Broker.
    taskInputData?: any;                // Input data needed for the task execution.

    parentTask?: ParentTask; // Optional parent task information for tracking task hierarchies.
    taskGroupId?: string; // Optional group ID to group related subtasks together.

    constructor({ command, taskId, taskInputData, correlationId, taskInstanceId, parentTask, taskGroupId }: AgentTaskRequest) {
        this.command = command;
        this.taskId = taskId;
        this.taskInputData = taskInputData;
        this.correlationId = correlationId;
        this.taskInstanceId = taskInstanceId;
        this.parentTask = parentTask;
        this.taskGroupId = taskGroupId;
    }

    static fromHTTPRequest(req: any): AgentTaskRequest {

        // 1. Validate mandatory fields
        if (!req.body.command) throw new ValidationError(400, "Missing mandatory field: command");
        if (!req.body.taskId) throw new ValidationError(400, "Missing mandatory field: taskId");
        if (req.body.parentTask && !req.body.correlationId) throw new ValidationError(400, "Missing mandatory field: correlationId when parentTask is provided.");
        if (req.body.parentTask && !req.body.taskGroupId) throw new ValidationError(400, "Missing mandatory field: taskGroupId when parentTask is provided.");
        if (req.body.command.command === 'resume' && !req.body.command.completedTaskGroupId) throw new ValidationError(400, "Missing mandatory field: completedTaskGroupId for resume command. Received: " + JSON.stringify(req.body));

        // 2. Extract fields
        return new AgentTaskRequest({
            command: req.body.command,
            taskId: req.body.taskId,
            taskInputData: req.body.taskInputData || null,
            correlationId: req.body.correlationId || null,
            taskInstanceId: req.body.taskInstanceId || null,
            parentTask: req.body.parentTask || null,
            taskGroupId: req.body.taskGroupId || null,
        });
    }
}

export interface ParentTask {
    taskId: TaskId;         // Unique identifier of the parent task.   
    taskInstanceId: string; // Unique identifier for this specific execution of the parent task.
}

/**
 * Models the data returned from an Agent after executing a task.
 */
export class AgentTaskResponse {

    correlationId: string;  // Correlation ID to group related tasks together.
    stopReason: StopReason  // Reason why the task execution stopped.
    taskOutput?: any;       // Output data produced by the task execution.
    subtasks?: TaskGroup[]; // Information about any subtasks that need to be executed as part of this task. This is used for tasks that decompose into multiple subtasks.

    constructor({ correlationId, stopReason, taskOutput, subtasks }: AgentTaskResponse) {
        this.correlationId = correlationId;
        this.stopReason = stopReason;
        this.taskOutput = taskOutput;
        this.subtasks = subtasks;
    }

    static fromHTTPResponse(body: any): AgentTaskResponse {
        try {
            const parsed = JSON.parse(body);

            // Validate required fields
            if (!parsed.stopReason) throw new ValidationError(400, "Missing required field 'stopReason' in AgentTaskResponse.");
            if (!parsed.correlationId) throw new ValidationError(400, "Missing required field 'correlationId' in AgentTaskResponse. An Agent always needs to return the correlation ID it received when triggered.");

            if (parsed.stopReason === 'subtasks' && !parsed.subtasks) throw new ValidationError(400, "AgentTaskResponse with stopReason 'subtasks' must include 'subtasks' field.");

            return new AgentTaskResponse({
                correlationId: parsed.correlationId,
                stopReason: parsed.stopReason,
                taskOutput: parsed.taskOutput,
                subtasks: parsed.subtasks
            });

        } catch (error) {
            if (error instanceof SyntaxError) throw new TotoRuntimeError(500, `Failed to parse AgentTaskResponse from HTTP response body: ${body}`);
            throw error;
        }
    }
}

export interface TaskGroup {
    groupId: string;            // Unique Id of the group.
    tasks: TaskInfo[];          // List of tasks in the group.
}

export interface TaskInfo {
    taskId: TaskId;             // Unique identifier of the subtask to be executed.
    taskInputData?: any;        // Input data needed for the subtask execution.
}

export interface ParentTaskInfo {
    correlationId: string;
    taskId: string;
    taskInstanceId: string;
}

export type StopReason = "completed" | "failed" | "subtasks";

export interface Command {
    command: "start" | "resume";
    completedTaskGroupId?: string; // The ID of the group of subtasks that have been completed, triggering the resumption of the parent task.
}

export type TaskId = string;