
/**
 * Model for the message to agent as part of a conversation.
 */
export interface AgentConversationMessage {
    conversationId: string; // ID of the conversation to which the message belongs (if it's a new conversation, this can be generated by the server and returned in the response)
    messageId: string;      // ID of the message (can be generated by the client or the server)
    agentId: string;        // ID of the agent this message is directed to
    message: string;        // The user message content
    userEmail: string;     // Email of the user who sent the message (useful for personalization or follow-up)
}